name: 'Setup MoonBit'
description: 'Set up MoonBit CLI'
runs:
  using: 'composite'
  steps:
    - name: Install MoonBit
      shell: bash
      run: |
        curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
        echo "$HOME/.moon/bin" >> $GITHUB_PATH
    - name: Update registry
      shell: bash
      run: moon update